### ISSUE TITLE
Radar chart on skills results

### ISSUE THREAD

**Issue by stefanocudini** [DigitalCommonsLab/professioni_istat#11]
@napo  sto facendo delle prove.. ma.. forse metterci il radar con quei paraetri li.. potrebbe essere male.
Ne potremmo prendere solo alcuni massimo 5/7 fissi per ogni lavoro(semmai ce ne siano)
oppure aggiungerne troppi risulta un radar completamente confuso

![radar_jobs](https://user-images.githubusercontent.com/47107/42691467-78090f9c-86a8-11e8-84f2-d35a4aa8b058.gif)

**Comment by napo** [comment]
non ho capito bene la domanda.
Forse intendi che i parametri sono troppi?

**Comment by stefanocudini** [comment]
si forse 7 puo' essere il massimo

**Comment by stefanocudini** [comment]
si troppi ed anche l'altra questione e' che nei chart radar radar e'
immpirtante che il numero e l'ordine dei parametri sugli assi rimanga lo
stesso tra una professione e l'altra..
altrimenti quando si cambia professione e viene ri-renderizzato il radar si
ottengonon sempre "forme" diverse.
Per cui bisogna vedere se e' effettivamente il caso di usare un radar li..
forse no.
Se invece si allora vanno definiti gli assi/parametri da mostrare, che
siano sempre gli stessi per ogni professione, cosa un po difficile credo
per tutte le professioni.

Non so se mi sono spiegato, cmq tanto era giusto per prova il radar.

Il giorno sab 14 lug 2018 alle ore 23:08 Maurizio Napolitano <
notifications@github.com> ha scritto:
